apiVersion: v1
kind: Secret
metadata:
  name: backend-user-secret
stringData:
  application-secret.yml: |
    spring:
      datasource:
        username: user
        password: 1234
    jwt:
      expires-in: 86400 # 1day
      mobile-expires-in: 31536000
      table-expires-in: 31536000
      secret-key: AADfaskllewqwertyuiopasdfghjklm32dsfasdTG764Gdslkj298GsWg86G